import type {
  Agent,
  Application,
  ApplicationDoc,
  College,
  Enquiry,
  Lead,
  RawDataBatch,
  RawStudentRecord,
  StudentProfile,
  Voucher,
} from "./types";

export function daysAgo(days: number, hour = 11): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, Math.floor(Math.random() * 60), 0, 0);
  return d.toISOString();
}

const DOC_TEMPLATE: Omit<ApplicationDoc, "done">[] = [
  { id: "d1", name: "Class 10 Marksheet", required: true },
  { id: "d2", name: "Class 12 Marksheet", required: true },
  { id: "d3", name: "Transfer Certificate", required: true },
  { id: "d4", name: "ID / Aadhaar Proof", required: true },
  { id: "d5", name: "Passport Photos", required: true },
  { id: "d6", name: "Entrance Exam Scorecard", required: true },
  { id: "d7", name: "Caste / Income Certificate (if applicable)", required: false },
];

function docs(doneIds: string[]): ApplicationDoc[] {
  return DOC_TEMPLATE.map((d) => ({ ...d, done: doneIds.includes(d.id) }));
}

export const SEED_COLLEGES: College[] = [
  {
    id: "rvce",
    name: "RV College of Engineering",
    shortName: "RVCE",
    city: "Bengaluru",
    established: 1963,
    rating: 4.6,
    type: "Private",
    about:
      "RVCE is among India's most sought-after private engineering institutes, known for its strong industry placement cell, research culture and a sprawling campus in the heart of Bengaluru's tech corridor.",
    tags: ["NAAC A++", "Autonomous", "AICTE Approved", "Top-10 Engineering"],
    accreditation: ["NAAC A++", "NBA All Branches", "AICTE Approved", "Autonomous"],
    ranking: "NIRF Engineering #45",
    admissions: {
      exam: "KCET / JEE Main",
      applicationFee: 500,
      deadline: "July 15, 2026",
      minGPA: "60% in PCM",
      notes: "50% lateral entry via CET counselling.",
    },
    costs: { hostelMonthly: 12000, livingMonthly: 18000 },
    scholarships: {
      available: true,
      details: "Up to ₹1,20,000 merit scholarships + Orion assured voucher applies.",
      budget: 100000,
    },
    programs: [
      { name: "B.E. Computer Science", stream: "Engineering", durationYears: 4, annualFee: 320000, totalFee: 1280000, avgPlacement: 1800000, eligibility: "60% in PCM + KCET/JEE", intakes: ["July"], seats: 240 },
      { name: "B.E. AI & Machine Learning", stream: "Engineering", durationYears: 4, annualFee: 340000, totalFee: 1360000, avgPlacement: 2000000, eligibility: "70% in PCM + JEE", intakes: ["July"], seats: 60 },
      { name: "B.E. Electronics & Comm.", stream: "Engineering", durationYears: 4, annualFee: 290000, totalFee: 1160000, avgPlacement: 1400000, eligibility: "60% in PCM + KCET/JEE", intakes: ["July"], seats: 240 },
      { name: "B.E. Information Science", stream: "Engineering", durationYears: 4, annualFee: 300000, totalFee: 1200000, avgPlacement: 1300000, eligibility: "60% in PCM", intakes: ["July"], seats: 120 },
      { name: "B.E. Mechanical", stream: "Engineering", durationYears: 4, annualFee: 280000, totalFee: 1120000, avgPlacement: 950000, eligibility: "55% in PCM", intakes: ["July"], seats: 180 },
      { name: "M.Tech Computer Science", stream: "Engineering", durationYears: 2, annualFee: 210000, totalFee: 420000, avgPlacement: 1600000, eligibility: "60% in B.E./B.Tech", intakes: ["July"], seats: 30 },
    ],
    placementPct: 92,
    highestPlacement: 6400000,
    intake: 1200,
    facilities: ["Central Library", "Sports Complex", "Startup Incubator", "Hostels", "Wi-Fi Campus", "Smart Classrooms"],
    reels: [
      { id: "rv1", title: "Campus Walkthrough", duration: "0:42", from: "#0F0D2E", to: "#2A256D" },
      { id: "rv2", title: "Placement Day 2025", duration: "1:10", from: "#0A1429", to: "#0F0D2E" },
      { id: "rv3", title: "Student Life", duration: "0:55", from: "#F5B700", to: "#0A1429" },
    ],
    sourceWebsite: "https://www.rvce.edu.in",
  },
  {
    id: "bmsce",
    name: "BMS College of Engineering",
    shortName: "BMSCE",
    city: "Bengaluru",
    established: 1946,
    rating: 4.3,
    type: "Private",
    about:
      "One of the oldest engineering colleges in India, BMSCE blends a century-old legacy with modern labs, active student clubs and a strong alumni network across tech and manufacturing.",
    tags: ["NAAC A+", "Autonomous", "Heritage Campus"],
    accreditation: ["NAAC A+", "NBA Accredited", "AICTE Approved", "Autonomous"],
    ranking: "NIRF Engineering #61",
    admissions: {
      exam: "KCET / COMEDK",
      applicationFee: 700,
      deadline: "June 30, 2026",
      minGPA: "60% in PCM",
    },
    costs: { hostelMonthly: 11000, livingMonthly: 16000 },
    scholarships: { available: true, details: "Merit scholarships + Orion assured voucher applies.", budget: 90000 },
    programs: [
      { name: "B.E. Computer Science", stream: "Engineering", durationYears: 4, annualFee: 260000, totalFee: 1040000, avgPlacement: 1250000, eligibility: "60% in PCM", intakes: ["July"], seats: 180 },
      { name: "B.E. Information Science", stream: "Engineering", durationYears: 4, annualFee: 250000, totalFee: 1000000, avgPlacement: 1100000, eligibility: "55% in PCM", intakes: ["July"], seats: 120 },
      { name: "B.E. Electronics & Comm.", stream: "Engineering", durationYears: 4, annualFee: 255000, totalFee: 1020000, avgPlacement: 1050000, eligibility: "55% in PCM", intakes: ["July"], seats: 150 },
      { name: "B.E. Civil", stream: "Engineering", durationYears: 4, annualFee: 230000, totalFee: 920000, avgPlacement: 600000, eligibility: "50% in PCM", intakes: ["July"], seats: 120 },
      { name: "B.E. Mechanical", stream: "Engineering", durationYears: 4, annualFee: 240000, totalFee: 960000, avgPlacement: 750000, eligibility: "50% in PCM", intakes: ["July"], seats: 120 },
    ],
    placementPct: 88,
    highestPlacement: 4200000,
    intake: 960,
    facilities: ["Library", "Hostels", "Auditorium", "R&D Labs", "Sports Ground"],
    reels: [
      { id: "bm1", title: "Main Campus Tour", duration: "1:05", from: "#0F0D2E", to: "#2A4D8F" },
      { id: "bm2", title: "Fest 'Sparsh' Highlights", duration: "0:48", from: "#F5B700", to: "#0F0D2E" },
    ],
    sourceWebsite: "https://bmsce.ac.in",
  },
  {
    id: "christ",
    name: "Christ University",
    shortName: "Christ",
    city: "Bengaluru",
    established: 1969,
    rating: 4.4,
    type: "Private",
    about:
      "A multi-disciplinary university with a thriving campus culture, Christ offers globally benchmarked programs in commerce, business and humanities with strong placement support.",
    tags: ["NAAC A+", "UGC", "Multi-Disciplinary"],
    accreditation: ["NAAC A+", "UGC Recognized", "Autonomous"],
    ranking: "NIRF University #90",
    admissions: {
      exam: "CUET / Christ Entrance",
      applicationFee: 1000,
      deadline: "April 30, 2026",
      minGPA: "50% in 12th",
    },
    costs: { hostelMonthly: 15000, livingMonthly: 20000 },
    scholarships: { available: true, details: "Merit + sports scholarships + Orion voucher applies.", budget: 85000 },
    programs: [
      { name: "MBA", stream: "MBA", durationYears: 2, annualFee: 650000, totalFee: 1300000, avgPlacement: 1200000, eligibility: "Graduate + CUET PG", intakes: ["July", "January"], seats: 240 },
      { name: "BBA", stream: "Commerce", durationYears: 3, annualFee: 340000, totalFee: 1020000, avgPlacement: 750000, eligibility: "50% in 12th", intakes: ["July"], seats: 300 },
      { name: "B.Com", stream: "Commerce", durationYears: 3, annualFee: 220000, totalFee: 660000, avgPlacement: 580000, eligibility: "50% in 12th", intakes: ["July"], seats: 480 },
      { name: "B.Com (Hons.)", stream: "Commerce", durationYears: 3, annualFee: 260000, totalFee: 780000, avgPlacement: 650000, eligibility: "55% in 12th", intakes: ["July"], seats: 120 },
      { name: "M.Sc Data Science", stream: "Engineering", durationYears: 2, annualFee: 420000, totalFee: 840000, avgPlacement: 1500000, eligibility: "60% in UG", intakes: ["July"], seats: 60 },
    ],
    placementPct: 85,
    highestPlacement: 3500000,
    intake: 5000,
    facilities: ["AC Classrooms", "Library", "Hostels", "Sports", "Cafeterias", "Innovation Labs"],
    reels: [
      { id: "ch1", title: "Campus Life", duration: "0:38", from: "#0F0D2E", to: "#4A3F8F" },
      { id: "ch2", title: "MBA Orientation", duration: "0:52", from: "#F5B700", to: "#0F0D2E" },
    ],
    sourceWebsite: "https://www.christuniversity.in",
  },
  {
    id: "manipal",
    name: "Manipal Institute of Technology",
    shortName: "MIT",
    city: "Manipal",
    established: 1957,
    rating: 4.5,
    type: "Private",
    about:
      "Set on a lush 300-acre campus, MIT Manipal offers world-class engineering education with a strong emphasis on research, international exchange and a massive residential community.",
    tags: ["NAAC A++", "Residential Campus", "Research Focused"],
    accreditation: ["NAAC A++", "NBA Accredited", "AICTE Approved"],
    ranking: "NIRF Engineering #42",
    admissions: {
      exam: "MET / JEE Main",
      applicationFee: 600,
      deadline: "June 20, 2026",
      minGPA: "60% in PCM",
    },
    costs: { hostelMonthly: 14000, livingMonthly: 20000 },
    scholarships: { available: true, details: "Merit scholarships + Orion assured voucher applies.", budget: 110000 },
    programs: [
      { name: "B.Tech Computer Science", stream: "Engineering", durationYears: 4, annualFee: 440000, totalFee: 1760000, avgPlacement: 1700000, eligibility: "60% in PCM + MET", intakes: ["July", "November"], seats: 300 },
      { name: "B.Tech AI & Data Science", stream: "Engineering", durationYears: 4, annualFee: 460000, totalFee: 1840000, avgPlacement: 1800000, eligibility: "65% in PCM", intakes: ["July"], seats: 120 },
      { name: "B.Tech Electronics & Comm.", stream: "Engineering", durationYears: 4, annualFee: 420000, totalFee: 1680000, avgPlacement: 1300000, eligibility: "60% in PCM", intakes: ["July", "November"], seats: 240 },
      { name: "B.Tech Mechanical", stream: "Engineering", durationYears: 4, annualFee: 390000, totalFee: 1560000, avgPlacement: 850000, eligibility: "60% in PCM", intakes: ["July"], seats: 180 },
      { name: "B.Tech Aerospace", stream: "Engineering", durationYears: 4, annualFee: 410000, totalFee: 1640000, avgPlacement: 900000, eligibility: "60% in PCM", intakes: ["July"], seats: 90 },
      { name: "M.Tech VLSI", stream: "Engineering", durationYears: 2, annualFee: 280000, totalFee: 560000, avgPlacement: 1200000, eligibility: "60% in B.E./B.Tech", intakes: ["July"], seats: 60 },
    ],
    placementPct: 90,
    highestPlacement: 5600000,
    intake: 1800,
    facilities: ["Lake-Front Campus", "Hostels", "Sports Arena", "Flight Simulator Lab", "Central Library"],
    reels: [
      { id: "mit1", title: "300-Acre Campus", duration: "1:20", from: "#0A1429", to: "#1C6B4F" },
      { id: "mit2", title: "TechTatva Festival", duration: "0:45", from: "#F5B700", to: "#0F0D2E" },
    ],
    sourceWebsite: "https://manipal.edu/mit",
  },
  {
    id: "nmims",
    name: "NMIMS University",
    shortName: "NMIMS",
    city: "Mumbai",
    established: 1981,
    rating: 4.6,
    type: "Private",
    about:
      "A leading B-school in the financial capital, NMIMS is renowned for its industry-aligned MBA, rigorous pedagogy and placement outcomes in consulting, finance and tech.",
    tags: ["NAAC A+", "Top B-School", "Mumbai"],
    accreditation: ["NAAC A+", "UGC Recognized", "AICTE Approved"],
    ranking: "NIRF Management #12",
    admissions: {
      exam: "NMIMS NPAT / CAT",
      applicationFee: 2000,
      deadline: "May 31, 2026",
      minGPA: "55% in UG / 12th",
    },
    costs: { hostelMonthly: 18000, livingMonthly: 25000 },
    scholarships: { available: true, details: "Merit-cum-means + Orion assured voucher applies.", budget: 150000 },
    programs: [
      { name: "MBA Core", stream: "MBA", durationYears: 2, annualFee: 980000, totalFee: 1960000, avgPlacement: 2200000, eligibility: "Graduate + NPAT/CAT", intakes: ["July"], seats: 600 },
      { name: "MBA Fintech", stream: "MBA", durationYears: 2, annualFee: 1020000, totalFee: 2040000, avgPlacement: 2400000, eligibility: "Graduate + NPAT", intakes: ["July"], seats: 120 },
      { name: "BBA", stream: "Commerce", durationYears: 3, annualFee: 480000, totalFee: 1440000, avgPlacement: 900000, eligibility: "55% in 12th", intakes: ["July"], seats: 420 },
      { name: "B.Com (Hons.)", stream: "Commerce", durationYears: 3, annualFee: 240000, totalFee: 720000, avgPlacement: 650000, eligibility: "50% in 12th", intakes: ["July"], seats: 300 },
      { name: "B.Tech Computer Science", stream: "Engineering", durationYears: 4, annualFee: 460000, totalFee: 1840000, avgPlacement: 1200000, eligibility: "60% in PCM", intakes: ["July"], seats: 240 },
    ],
    placementPct: 91,
    highestPlacement: 7800000,
    intake: 1200,
    facilities: ["AC Campus", "Placement Cell", "Hostels", "Finance Lab", "Library"],
    reels: [
      { id: "nm1", title: "MBA Campus Tour", duration: "1:02", from: "#0F0D2E", to: "#5B8F2A" },
      { id: "nm2", title: "Placement Season", duration: "0:58", from: "#F5B700", to: "#0F0D2E" },
    ],
    sourceWebsite: "https://www.nmims.edu",
  },
  {
    id: "dtu",
    name: "Delhi Technological University",
    shortName: "DTU",
    city: "New Delhi",
    established: 1941,
    rating: 4.5,
    type: "Government",
    about:
      "A premier government technical university, DTU consistently ranks among India's top engineering institutes with some of the strongest placement records in the capital.",
    tags: ["Government", "NAAC A+", "Top Engineering"],
    accreditation: ["NAAC A+", "AICTE Approved", "UGC", "Government"],
    ranking: "NIRF Engineering #25",
    admissions: {
      exam: "JEE Main (JoSAA)",
      applicationFee: 0,
      deadline: "Via JoSAA counselling",
      minGPA: "95+ JEE Main percentile",
      notes: "DTE Delhi state counselling also accepted.",
    },
    costs: { hostelMonthly: 8000, livingMonthly: 15000 },
    scholarships: { available: true, details: "Merit-cum-means + Orion assured voucher applies.", budget: 70000 },
    programs: [
      { name: "B.Tech Computer Science", stream: "Engineering", durationYears: 4, annualFee: 340000, totalFee: 1360000, avgPlacement: 2000000, eligibility: "JEE Main 98%+", intakes: ["July"], seats: 180 },
      { name: "B.Tech IT", stream: "Engineering", durationYears: 4, annualFee: 330000, totalFee: 1320000, avgPlacement: 1800000, eligibility: "JEE Main 96%+", intakes: ["July"], seats: 120 },
      { name: "B.Tech Electronics & Comm.", stream: "Engineering", durationYears: 4, annualFee: 320000, totalFee: 1280000, avgPlacement: 1500000, eligibility: "JEE Main 92%+", intakes: ["July"], seats: 120 },
      { name: "B.Tech Mechanical", stream: "Engineering", durationYears: 4, annualFee: 290000, totalFee: 1160000, avgPlacement: 900000, eligibility: "JEE Main 85%+", intakes: ["July"], seats: 180 },
      { name: "M.Tech Computer Science", stream: "Engineering", durationYears: 2, annualFee: 140000, totalFee: 280000, avgPlacement: 1100000, eligibility: "GATE qualified", intakes: ["July"], seats: 60 },
    ],
    placementPct: 93,
    highestPlacement: 5200000,
    intake: 2400,
    facilities: ["Green Campus", "Hostels", "Sports", "Research Centres", "Library"],
    reels: [
      { id: "dt1", title: "Campus Drone Tour", duration: "1:15", from: "#0A1429", to: "#2A6B8F" },
      { id: "dt2", title: "Hackathon 2025", duration: "0:40", from: "#F5B700", to: "#0F0D2E" },
    ],
    sourceWebsite: "https://www.dtu.ac.in",
  },
  {
    id: "nid",
    name: "National Institute of Design",
    shortName: "NID",
    city: "Ahmedabad",
    established: 1961,
    rating: 4.7,
    type: "Government",
    about:
      "India's premier design school, NID Ahmedabad is a breeding ground for the country's top product designers, UX leads and design entrepreneurs.",
    tags: ["Government", "Design Leader", "Creative"],
    accreditation: ["Ministry of Education", "Autonomous", "Government"],
    ranking: "QS Design #50 Asia",
    admissions: {
      exam: "NID DAT",
      applicationFee: 3000,
      deadline: "January 15, 2026",
      minGPA: "Pass in 12th",
      notes: "Portfolio + studio test + interview rounds.",
    },
    costs: { hostelMonthly: 9000, livingMonthly: 14000 },
    scholarships: { available: true, details: "Merit + Orion assured voucher applies.", budget: 60000 },
    programs: [
      { name: "Bachelor of Design", stream: "Design", durationYears: 4, annualFee: 290000, totalFee: 1160000, avgPlacement: 1000000, eligibility: "NID DAT", intakes: ["July"], seats: 40 },
      { name: "B.Des Communication Design", stream: "Design", durationYears: 4, annualFee: 290000, totalFee: 1160000, avgPlacement: 950000, eligibility: "NID DAT", intakes: ["July"], seats: 40 },
      { name: "B.Des Interaction Design", stream: "Design", durationYears: 4, annualFee: 310000, totalFee: 1240000, avgPlacement: 1200000, eligibility: "NID DAT", intakes: ["July"], seats: 20 },
      { name: "PG Product Design", stream: "Design", durationYears: 2, annualFee: 350000, totalFee: 700000, avgPlacement: 1300000, eligibility: "NID DAT (M.Des)", intakes: ["July"], seats: 20 },
    ],
    placementPct: 87,
    highestPlacement: 3000000,
    intake: 180,
    facilities: ["Design Studios", "Material Labs", "Workshops", "Library", "Crafts Campus"],
    reels: [
      { id: "nid1", title: "Design Studios", duration: "0:50", from: "#0F0D2E", to: "#8F5B2A" },
      { id: "nid2", title: "Graduation Show", duration: "1:00", from: "#F5B700", to: "#0F0D2E" },
    ],
    sourceWebsite: "https://www.nid.edu",
  },
  {
    id: "sjcc",
    name: "St. Joseph's College of Commerce",
    shortName: "SJCC",
    city: "Bengaluru",
    established: 1882,
    rating: 4.3,
    type: "Private",
    about:
      "A legacy institution in Bengaluru's commerce space, SJCC offers affordable, rigorous commerce and business programs with strong placements in finance and consulting.",
    tags: ["NAAC A+", "Affordable", "Finance Hub"],
    accreditation: ["NAAC A+", "UGC Recognized", "Autonomous"],
    ranking: "Top Commerce College, Bengaluru",
    admissions: {
      exam: "SJCC Entrance / Merit",
      applicationFee: 500,
      deadline: "June 15, 2026",
      minGPA: "50% in 12th",
    },
    costs: { hostelMonthly: 9000, livingMonthly: 14000 },
    scholarships: { available: true, details: "Merit + Orion assured voucher applies.", budget: 65000 },
    programs: [
      { name: "B.Com", stream: "Commerce", durationYears: 3, annualFee: 140000, totalFee: 420000, avgPlacement: 620000, eligibility: "50% in 12th", intakes: ["July"], seats: 480 },
      { name: "B.Com (Hons.)", stream: "Commerce", durationYears: 3, annualFee: 160000, totalFee: 480000, avgPlacement: 680000, eligibility: "55% in 12th", intakes: ["July"], seats: 180 },
      { name: "BBA", stream: "Commerce", durationYears: 3, annualFee: 180000, totalFee: 540000, avgPlacement: 680000, eligibility: "50% in 12th", intakes: ["July"], seats: 300 },
      { name: "BBA Fintech", stream: "Commerce", durationYears: 3, annualFee: 200000, totalFee: 600000, avgPlacement: 800000, eligibility: "55% in 12th", intakes: ["July"], seats: 120 },
    ],
    placementPct: 80,
    highestPlacement: 1500000,
    intake: 900,
    facilities: ["Heritage Campus", "Library", "Auditorium", "Sports"],
    reels: [
      { id: "sj1", title: "Heritage Campus", duration: "0:35", from: "#0F0D2E", to: "#5B5B8F" },
      { id: "sj2", title: "Finance Fest", duration: "0:44", from: "#F5B700", to: "#0F0D2E" },
    ],
    sourceWebsite: "https://www.sjcc.edu.in",
  },
  {
    id: "myra",
    name: "MYRA School of Business",
    shortName: "MYRA",
    city: "Mysuru",
    established: 2012,
    rating: 4.4,
    type: "Private",
    about:
      "MYRA School of Business is an AICTE-approved business school in Mysuru built around an industry-immersed PGDM, global faculty and a career success program designed for emerging business leaders.",
    tags: ["AICTE Approved", "PGDM", "Dual Specialisation", "Mysuru"],
    accreditation: ["AICTE Approved", "Mysore Royal Academy", "Autonomous"],
    ranking: "IIRF PGDM #18",
    admissions: {
      exam: "CAT / XAT / CMAT / MET",
      applicationFee: 1500,
      deadline: "June 30, 2026",
      minGPA: "50% in graduation",
      notes: "Shortlisted candidates complete a personal interview and written assessment.",
    },
    costs: { hostelMonthly: 18000, livingMonthly: 16000 },
    scholarships: {
      available: true,
      details: "Merit, entrance-score and performance-based scholarships, with awards up to ₹5,00,000.",
      budget: 100000,
    },
    programs: [
      { name: "PGDM — Finance", stream: "MBA", durationYears: 2, annualFee: 605000, totalFee: 1210000, avgPlacement: 906000, eligibility: "50% in graduation + CAT/XAT/CMAT/MET", intakes: ["July"], seats: 180 },
      { name: "PGDM — Marketing & Sales", stream: "MBA", durationYears: 2, annualFee: 605000, totalFee: 1210000, avgPlacement: 906000, eligibility: "50% in graduation + CAT/XAT/CMAT/MET", intakes: ["July"], seats: 180 },
      { name: "PGDM — Business Analytics", stream: "MBA", durationYears: 2, annualFee: 605000, totalFee: 1210000, avgPlacement: 906000, eligibility: "50% in graduation + CAT/XAT/CMAT/MET", intakes: ["July"], seats: 120 },
      { name: "PGDM — HR & Operations", stream: "MBA", durationYears: 2, annualFee: 605000, totalFee: 1210000, avgPlacement: 906000, eligibility: "50% in graduation + CAT/XAT/CMAT/MET", intakes: ["July"], seats: 120 },
    ],
    placementPct: 96,
    highestPlacement: 3500000,
    intake: 600,
    facilities: ["8.5-Acre Campus", "Floating Classroom", "Leadership Labs", "Hostels", "Career Success Centre"],
    reels: [
      { id: "myra1", title: "MYRA Campus", duration: "0:52", from: "#5A1F2C", to: "#0F0D2E" },
      { id: "myra2", title: "Learning Spaces", duration: "0:44", from: "#C47A2C", to: "#0F0D2E" },
    ],
    coverImage: "https://myra.ac.in/images/ogimagesmyra.jpg",
    photos: ["https://myra.ac.in/images/cse-1.jpg?itok=bYYj2sp3"],
    sourceWebsite: "https://myra.ac.in",
  },
  {
    id: "doon",
    name: "Doon Business School",
    shortName: "DBS",
    city: "Dehradun",
    established: 2009,
    rating: 4.2,
    type: "Private",
    about:
      "Doon Business School is a constituent school of DBS Global University offering industry-focused management programs in a residential campus near Dehradun's Selaqui education corridor.",
    tags: ["DBS Global University", "AICTE Approved", "Residential", "350+ Recruiters"],
    accreditation: ["AICTE Approved", "DBS Global University", "UTU Affiliated"],
    ranking: "Top Emerging B-School",
    admissions: {
      exam: "CAT / XAT / CMAT / MAT / DBS Entrance",
      applicationFee: 1200,
      deadline: "July 15, 2026",
      minGPA: "50% in graduation",
      notes: "Admission includes profile review, entrance score and personal interview.",
    },
    costs: { hostelMonthly: 15000, livingMonthly: 14000 },
    scholarships: {
      available: true,
      details: "Entrance-score and merit scholarships are available across MBA and PGDM programs.",
      budget: 80000,
    },
    programs: [
      { name: "MBA — General Management", stream: "MBA", durationYears: 2, annualFee: 330000, totalFee: 660000, avgPlacement: 815000, eligibility: "50% in graduation + accepted entrance score", intakes: ["July"], seats: 240 },
      { name: "PGDM — Digital Business", stream: "MBA", durationYears: 2, annualFee: 360000, totalFee: 720000, avgPlacement: 815000, eligibility: "50% in graduation + accepted entrance score", intakes: ["July"], seats: 180 },
      { name: "PGDM — Data Analytics", stream: "MBA", durationYears: 2, annualFee: 360000, totalFee: 720000, avgPlacement: 815000, eligibility: "50% in graduation + accepted entrance score", intakes: ["July"], seats: 120 },
      { name: "PGDM — Marketing & Finance", stream: "MBA", durationYears: 2, annualFee: 360000, totalFee: 720000, avgPlacement: 815000, eligibility: "50% in graduation + accepted entrance score", intakes: ["July"], seats: 180 },
    ],
    placementPct: 88,
    highestPlacement: 2400000,
    intake: 900,
    facilities: ["Residential Hostels", "Modern Classrooms", "Sports Facilities", "Industry Projects", "Career Cell"],
    reels: [
      { id: "dbs1", title: "DBS Campus", duration: "0:48", from: "#0B376B", to: "#0F0D2E" },
      { id: "dbs2", title: "Student Life", duration: "0:51", from: "#2D7A63", to: "#0F0D2E" },
    ],
    coverImage: "https://doonbusinessschool.com/images/slides/banner1.jpg",
    photos: ["https://doonbusinessschool.com/images/slides/banner1.jpg"],
    sourceWebsite: "https://doonbusinessschool.com",
  },
  {
    id: "pibm",
    name: "Pune Institute of Business Management",
    shortName: "PIBM",
    city: "Pune",
    established: 2007,
    rating: 4.3,
    type: "Private",
    about:
      "PIBM is a residential business school near Pune offering AICTE-approved PGDM and SPPU-affiliated MBA programs with industry visits, live projects and dual internships.",
    tags: ["AICTE Approved", "AIU Recognised", "SPPU Affiliated", "Residential"],
    accreditation: ["AICTE Approved", "AIU Recognised", "NAAC", "NBA"],
    ranking: "Top B-School, Pune",
    admissions: {
      exam: "CAT / XAT / CMAT / MAT / ATMA",
      applicationFee: 1500,
      deadline: "April 10, 2026",
      minGPA: "50% in 10th, 12th and graduation",
      notes: "PIBM offers both PGDM and MBA tracks; MBA is affiliated to SPPU.",
    },
    costs: { hostelMonthly: 16667, livingMonthly: 14000 },
    scholarships: {
      available: true,
      details: "Merit and entrance-based scholarships are available. Residential fee is shown separately from tuition.",
      budget: 120000,
    },
    programs: [
      { name: "PGDM — General Management", stream: "MBA", durationYears: 2, annualFee: 447500, totalFee: 895000, avgPlacement: 910000, eligibility: "50% in 10th, 12th and graduation", intakes: ["July"], seats: 360 },
      { name: "MBA — Marketing", stream: "MBA", durationYears: 2, annualFee: 447500, totalFee: 895000, avgPlacement: 910000, eligibility: "50% in 10th, 12th and graduation", intakes: ["July"], seats: 240 },
      { name: "MBA — Finance", stream: "MBA", durationYears: 2, annualFee: 447500, totalFee: 895000, avgPlacement: 910000, eligibility: "50% in 10th, 12th and graduation", intakes: ["July"], seats: 240 },
      { name: "PGDM — Business Analytics", stream: "MBA", durationYears: 2, annualFee: 447500, totalFee: 895000, avgPlacement: 910000, eligibility: "50% in 10th, 12th and graduation", intakes: ["July"], seats: 180 },
    ],
    placementPct: 91,
    highestPlacement: 1800000,
    intake: 1200,
    facilities: ["Residential Campus", "Industry Labs", "Live Projects", "Dual Internships", "Sports Complex"],
    reels: [
      { id: "pibm1", title: "PIBM Campus", duration: "0:56", from: "#1B4B6F", to: "#0F0D2E" },
      { id: "pibm2", title: "Industry Learning", duration: "0:42", from: "#B26A1A", to: "#0F0D2E" },
    ],
    coverImage: "https://www.pibm.in/images/sliders/Slider-1.1.webp",
    photos: ["https://www.pibm.in/images/sliders/Slider-2.1.webp"],
    sourceWebsite: "https://www.pibm.in",
  },
  {
    id: "uwsb",
    name: "IQ City United World School of Business",
    shortName: "UWSB",
    city: "Kolkata",
    established: 2009,
    rating: 4.1,
    type: "Private",
    about:
      "IQ City UWSB Kolkata offers a two-year MBA with an industry-designed curriculum, internships, live projects and leadership development in the heart of Salt Lake Sector V.",
    tags: ["AICTE Approved", "Kolkata", "200+ Recruiters", "Industry Designed"],
    accreditation: ["AICTE Approved", "Vidyasagar University Affiliated"],
    ranking: "Top B-School, Kolkata",
    admissions: {
      exam: "CAT / CMAT / MAT / XAT / ATMA",
      applicationFee: 1000,
      deadline: "June 30, 2026",
      minGPA: "Graduate in any discipline",
      notes: "Selection includes group discussion, WAT, psychometric test and personal interview.",
    },
    costs: { hostelMonthly: 15000, livingMonthly: 13000 },
    scholarships: {
      available: true,
      details: "Merit scholarships and Orion counselling support are available. Confirm current fee and scholarship terms with admissions.",
      budget: 60000,
    },
    programs: [
      { name: "MBA — Marketing", stream: "MBA", durationYears: 2, annualFee: 300000, totalFee: 600000, avgPlacement: 600000, eligibility: "Graduate in any discipline + accepted entrance score", intakes: ["July"], seats: 180 },
      { name: "MBA — Finance", stream: "MBA", durationYears: 2, annualFee: 300000, totalFee: 600000, avgPlacement: 600000, eligibility: "Graduate in any discipline + accepted entrance score", intakes: ["July"], seats: 180 },
      { name: "MBA — Human Resources", stream: "MBA", durationYears: 2, annualFee: 300000, totalFee: 600000, avgPlacement: 600000, eligibility: "Graduate in any discipline + accepted entrance score", intakes: ["July"], seats: 120 },
      { name: "MBA — Business Analytics", stream: "MBA", durationYears: 2, annualFee: 300000, totalFee: 600000, avgPlacement: 600000, eligibility: "Graduate in any discipline + accepted entrance score", intakes: ["July"], seats: 120 },
    ],
    placementPct: 82,
    highestPlacement: 1400000,
    intake: 600,
    facilities: ["Salt Lake Sector V Campus", "Central Library", "Industry Projects", "Internship Cell", "Leadership Labs"],
    reels: [
      { id: "uw1", title: "UWSB Campus", duration: "0:47", from: "#347F73", to: "#0F0D2E" },
      { id: "uw2", title: "Student Projects", duration: "0:39", from: "#B77D32", to: "#0F0D2E" },
    ],
    coverImage: "https://uwsbkolkata.com/wp-content/uploads/2025/01/mba-img-1.webp",
    photos: ["https://uwsbkolkata.com/wp-content/themes/custom/assets/images/inner-banner/courses.jpg"],
    sourceWebsite: "https://uwsbkolkata.com",
    feesTbc: true,
  },
  {
    id: "gims",
    name: "GNIOT Institute of Management Studies",
    shortName: "GIMS",
    city: "Greater Noida",
    established: 2020,
    rating: 4.2,
    type: "Private",
    about:
      "GIMS Greater Noida offers a two-year AICTE-approved PGDM with dual specialisations, trimester delivery, corporate projects and an active placement cell in Delhi-NCR.",
    tags: ["AICTE Approved", "HLACT Accredited", "Dual Specialisation", "Delhi-NCR"],
    accreditation: ["AICTE Approved", "HLACT UK", "IIM Bangalore Collaboration"],
    ranking: "NIRF Management 150–200",
    admissions: {
      exam: "CAT / MAT / XAT / CMAT / GAT",
      applicationFee: 1200,
      deadline: "July 31, 2026",
      minGPA: "50% in graduation",
      notes: "The two-year PGDM is offered through a trimester system with dual-specialisation electives.",
    },
    costs: { hostelMonthly: 13000, livingMonthly: 15000 },
    scholarships: {
      available: true,
      details: "Merit and entrance-based scholarships are available; current PGDM fee is shown as ₹8,55,000 total.",
      budget: 90000,
    },
    programs: [
      { name: "PGDM — Marketing", stream: "MBA", durationYears: 2, annualFee: 427500, totalFee: 855000, avgPlacement: 875000, eligibility: "50% in graduation + accepted entrance score", intakes: ["July"], seats: 240 },
      { name: "PGDM — Finance", stream: "MBA", durationYears: 2, annualFee: 427500, totalFee: 855000, avgPlacement: 875000, eligibility: "50% in graduation + accepted entrance score", intakes: ["July"], seats: 180 },
      { name: "PGDM — Business Analytics", stream: "MBA", durationYears: 2, annualFee: 427500, totalFee: 855000, avgPlacement: 875000, eligibility: "50% in graduation + accepted entrance score", intakes: ["July"], seats: 180 },
      { name: "PGDM — International Business", stream: "MBA", durationYears: 2, annualFee: 427500, totalFee: 855000, avgPlacement: 875000, eligibility: "50% in graduation + accepted entrance score", intakes: ["July"], seats: 120 },
    ],
    placementPct: 90,
    highestPlacement: 2345000,
    intake: 900,
    facilities: ["11-Acre Campus", "Smart Classrooms", "Corporate Resource Centre", "Hostels", "Chanakya Talk Series"],
    reels: [
      { id: "gims1", title: "GIMS Campus", duration: "0:50", from: "#1A3A6B", to: "#0F0D2E" },
      { id: "gims2", title: "Corporate Connect", duration: "0:43", from: "#E8A800", to: "#0F0D2E" },
    ],
    coverImage: "https://www.gims.net.in/img/slider/gims-home-website-slide-1-new.webp",
    photos: ["https://www.gims.net.in/img/newhome/life-at-gims-2.webp"],
    sourceWebsite: "https://www.gims.net.in",
  },
];

export const SEED_RAW_BATCHES: RawDataBatch[] = [
  { id: "batch-demo", fileName: "orion-demo-student-raw-data.xlsx", sheetName: "Student Raw Data", importedAt: daysAgo(0, 8), importedBy: "Superadmin", rowCount: 16, headers: ["Full Name", "Phone", "City", "Preferred College", "Preferred Program", "Score Band", "Budget Range"] },
];

export const SEED_RAW_STUDENTS: RawStudentRecord[] = [
  { id: "raw-demo-1", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Ananya Das", phone: "+91 98765 10001", email: "ananya.demo@example.com", city: "Guwahati", state: "Assam", stream: "MBA", scoreBand: "90+", entranceExam: "CAT", entranceScore: "88 percentile", preferredCollege: "MYRA School of Business", preferredProgram: "PGDM — Business Analytics", budgetRange: "₹10L–₹15L", hostelRequired: true, loanRequired: false, admissionTimeline: "This admission cycle", assignedAgent: "agent-priya", status: "Assigned", callStatus: "Not Called", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-2", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Rahul Bora", phone: "+91 98765 10002", email: "rahul.demo@example.com", city: "Dibrugarh", state: "Assam", stream: "MBA", scoreBand: "75-90", entranceExam: "CMAT", entranceScore: "78 percentile", preferredCollege: "GNIOT Institute of Management Studies", preferredProgram: "PGDM — Finance", budgetRange: "₹5L–₹10L", hostelRequired: true, loanRequired: true, admissionTimeline: "Within 1 month", assignedAgent: "agent-rohit", status: "Assigned", callStatus: "Not Called", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-3", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Nandita Saikia", phone: "+91 98765 10003", email: "nandita.demo@example.com", city: "Jorhat", state: "Assam", stream: "Commerce", scoreBand: "75-90", entranceExam: "MAT", entranceScore: "72 percentile", preferredCollege: "Doon Business School", preferredProgram: "MBA — General Management", budgetRange: "₹5L–₹10L", hostelRequired: true, loanRequired: false, admissionTimeline: "This admission cycle", assignedAgent: "agent-rohit", status: "Assigned", callStatus: "Not Called", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-4", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Priyanka Hazarika", phone: "+91 98765 10004", email: "priyanka.demo@example.com", city: "Silchar", state: "Assam", stream: "MBA", scoreBand: "60-75", entranceExam: "CAT", entranceScore: "64 percentile", preferredCollege: "Pune Institute of Business Management", preferredProgram: "PGDM — General Management", budgetRange: "₹10L–₹15L", hostelRequired: true, loanRequired: true, admissionTimeline: "Within 3 months", assignedAgent: "agent-priya", status: "Assigned", callStatus: "Not Called", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-5", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Sourav Borah", phone: "+91 98765 10005", email: "sourav.demo@example.com", city: "Tezpur", state: "Assam", stream: "Engineering", scoreBand: "90+", entranceExam: "JEE Main", entranceScore: "92 percentile", preferredCollege: "RV College of Engineering", preferredProgram: "B.E. Computer Science", budgetRange: "₹10L–₹15L", hostelRequired: true, loanRequired: false, admissionTimeline: "This admission cycle", assignedAgent: "agent-rohit", status: "Assigned", callStatus: "Connected", interestStatus: "Interested", remarks: [] },
  { id: "raw-demo-6", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Ishika Kalita", phone: "+91 98765 10006", email: "ishika.demo@example.com", city: "Nagaon", state: "Assam", stream: "Commerce", scoreBand: "75-90", entranceExam: "CUET", entranceScore: "81 percentile", preferredCollege: "Christ University", preferredProgram: "BBA", budgetRange: "₹5L–₹10L", hostelRequired: false, loanRequired: false, admissionTimeline: "Within 1 month", assignedAgent: "agent-priya", status: "Assigned", callStatus: "Not Called", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-7", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Deepjyoti Kalita", phone: "+91 98765 10007", email: "deepjyoti.demo@example.com", city: "Guwahati", state: "Assam", stream: "MBA", scoreBand: "75-90", entranceExam: "CAT", entranceScore: "76 percentile", preferredCollege: "NMIMS University", preferredProgram: "MBA Core", budgetRange: "₹15L–₹20L", hostelRequired: true, loanRequired: true, admissionTimeline: "This admission cycle", assignedAgent: "agent-rohit", status: "Assigned", callStatus: "No Answer", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-8", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Moumita Baruah", phone: "+91 98765 10008", email: "moumita.demo@example.com", city: "Dibrugarh", state: "Assam", stream: "Engineering", scoreBand: "75-90", entranceExam: "JEE Main", entranceScore: "82 percentile", preferredCollege: "BMS College of Engineering", preferredProgram: "B.E. Computer Science", budgetRange: "₹5L–₹10L", hostelRequired: true, loanRequired: false, admissionTimeline: "Within 3 months", assignedAgent: "agent-priya", status: "Assigned", callStatus: "Connected", interestStatus: "Interested", remarks: [] },
  { id: "raw-demo-9", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Arup Saikia", phone: "+91 98765 10009", email: "arup.demo@example.com", city: "Jorhat", state: "Assam", stream: "MBA", scoreBand: "60-75", entranceExam: "MAT", entranceScore: "68 percentile", preferredCollege: "Doon Business School", preferredProgram: "PGDM — Marketing & Finance", budgetRange: "₹5L–₹10L", hostelRequired: true, loanRequired: false, admissionTimeline: "Within 1 month", assignedAgent: "agent-rohit", status: "Assigned", callStatus: "Not Called", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-10", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Rinku Dutta", phone: "+91 98765 10010", email: "rinku.demo@example.com", city: "Tezpur", state: "Assam", stream: "MBA", scoreBand: "90+", entranceExam: "CAT", entranceScore: "91 percentile", preferredCollege: "Manipal Institute of Technology", preferredProgram: "B.Tech Computer Science", budgetRange: "₹15L–₹20L", hostelRequired: true, loanRequired: false, admissionTimeline: "This admission cycle", assignedAgent: "agent-priya", status: "Assigned", callStatus: "Connected", interestStatus: "Interested", remarks: [] },
  { id: "raw-demo-11", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Pranabjyoti Deka", phone: "+91 98765 10011", email: "pranab.demo@example.com", city: "Guwahati", state: "Assam", stream: "Engineering", scoreBand: "75-90", entranceExam: "JEE Main", entranceScore: "79 percentile", preferredCollege: "Delhi Technological University", preferredProgram: "B.Tech IT", budgetRange: "₹10L–₹15L", hostelRequired: true, loanRequired: true, admissionTimeline: "Within 3 months", assignedAgent: "agent-rohit", status: "Assigned", callStatus: "Busy", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-12", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Manash Protim Baruah", phone: "+91 98765 10012", email: "manash.demo@example.com", city: "Jorhat", state: "Assam", stream: "Design", scoreBand: "75-90", entranceExam: "NID DAT", entranceScore: "85 marks", preferredCollege: "National Institute of Design", preferredProgram: "B.Des Communication Design", budgetRange: "₹5L–₹10L", hostelRequired: true, loanRequired: false, admissionTimeline: "This admission cycle", assignedAgent: "agent-priya", status: "Assigned", callStatus: "Not Called", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-13", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Rimjhim Goswami", phone: "+91 98765 10013", email: "rimjhim.demo@example.com", city: "Guwahati", state: "Assam", stream: "MBA", scoreBand: "75-90", entranceExam: "CMAT", entranceScore: "74 percentile", preferredCollege: "Pune Institute of Business Management", preferredProgram: "PGDM — Business Analytics", budgetRange: "₹10L–₹15L", hostelRequired: true, loanRequired: true, admissionTimeline: "Within 1 month", assignedAgent: "agent-rohit", status: "Assigned", callStatus: "Connected", interestStatus: "Interested", remarks: [] },
  { id: "raw-demo-14", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Zakir Hussain", phone: "+91 98765 10014", email: "zakir.demo@example.com", city: "Dibrugarh", state: "Assam", stream: "Commerce", scoreBand: "60-75", entranceExam: "CUET", entranceScore: "69 percentile", preferredCollege: "St. Joseph's College of Commerce", preferredProgram: "B.Com (Hons.)", budgetRange: "₹5L–₹10L", hostelRequired: false, loanRequired: false, admissionTimeline: "Within 3 months", assignedAgent: "agent-priya", status: "Assigned", callStatus: "Not Called", interestStatus: "Not Assessed", remarks: [] },
  { id: "raw-demo-15", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Bedanta Baruah", phone: "+91 98765 10015", email: "bedanta.demo@example.com", city: "Tezpur", state: "Assam", stream: "MBA", scoreBand: "90+", entranceExam: "CAT", entranceScore: "87 percentile", preferredCollege: "MYRA School of Business", preferredProgram: "PGDM — Finance", budgetRange: "₹10L–₹15L", hostelRequired: true, loanRequired: false, admissionTimeline: "This admission cycle", assignedAgent: "agent-rohit", status: "Assigned", callStatus: "Connected", interestStatus: "Interested", remarks: [] },
  { id: "raw-demo-16", batchId: "batch-demo", sourceFile: "orion-demo-student-raw-data.xlsx", importedAt: daysAgo(0, 8), studentName: "Snigdha Choudhury", phone: "+91 98765 10016", email: "snigdha.demo@example.com", city: "Guwahati", state: "Assam", stream: "Engineering", scoreBand: "60-75", entranceExam: "JEE Main", entranceScore: "71 percentile", preferredCollege: "GNIOT Institute of Management Studies", preferredProgram: "PGDM — Marketing", budgetRange: "₹5L–₹10L", hostelRequired: true, loanRequired: false, admissionTimeline: "Within 1 month", assignedAgent: "agent-priya", status: "Assigned", callStatus: "No Answer", interestStatus: "Not Assessed", remarks: [] },
];

export const SEED_AGENTS: Agent[] = [
  { id: "a1", name: "Rohit Verma", avatarColor: "from-brand-950 to-brand-800", leadsAssigned: 42, callsMade: 128, callsConnected: 87, conversions: 19 },
  { id: "a2", name: "Priya Nair", avatarColor: "from-gold-600 to-gold-500", leadsAssigned: 38, callsMade: 141, callsConnected: 96, conversions: 23 },
  { id: "a3", name: "Aman Gupta", avatarColor: "from-brand-800 to-brand-950", leadsAssigned: 31, callsMade: 102, callsConnected: 61, conversions: 11 },
  { id: "a4", name: "Sara Khan", avatarColor: "from-gold-500 to-brand-950", leadsAssigned: 35, callsMade: 119, callsConnected: 74, conversions: 16 },
];

const RAW_SEED_LEADS: Omit<Lead, "leadType" | "scholarshipApplied">[] = [
  { id: "l1", name: "Rohan Desai", phone: "+91 98765 43210", email: "rohan.d@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 25000, lookingFor: "Admission Process & Loan", targetCollege: "RV College of Engineering", status: "New", callConnected: false, source: "Scholarship Checker", createdAt: daysAgo(0, 9), agent: "Rohit Verma" },
  { id: "l2", name: "Priya Sharma", phone: "+91 99880 11223", email: "priya.sh@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 60000, lookingFor: "Scholarship & Hostel", targetCollege: "NMIMS University", status: "New", callConnected: false, source: "Scholarship Checker", createdAt: daysAgo(0, 10), agent: "Priya Nair" },
  { id: "l3", name: "Arjun Mehta", phone: "+91 91234 56789", email: "arjun.m@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 24000, lookingFor: "College Comparison", targetCollege: "Manipal Institute of Technology", status: "Contacted", callConnected: true, source: "College Enquiry", createdAt: daysAgo(1, 15), agent: "Rohit Verma" },
  { id: "l4", name: "Sneha Iyer", phone: "+91 90080 11223", email: "sneha.iyer@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 20000, lookingFor: "Fee Structure", targetCollege: "BMS College of Engineering", status: "New", callConnected: false, source: "Scholarship Checker", createdAt: daysAgo(1, 17), agent: "Priya Nair" },
  { id: "l5", name: "Karan Patel", phone: "+91 98450 33445", email: "karan.p@gmail.com", intentLevel: "Cold", scholarshipUnlocked: 15000, lookingFor: "General Counselling", targetCollege: "Christ University", status: "Contacted", callConnected: true, source: "College Enquiry", createdAt: daysAgo(2, 12), agent: "Rohit Verma" },
  { id: "l6", name: "Ananya Gupta", phone: "+91 98111 22334", email: "ananya.g@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 36000, lookingFor: "Application Help", targetCollege: "Delhi Technological University", status: "Application Started", callConnected: true, source: "Scholarship Checker", createdAt: daysAgo(3, 10), agent: "Priya Nair" },
  { id: "l7", name: "Vikram Singh", phone: "+91 99000 55667", email: "vikram.s@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 18000, lookingFor: "Education Loan", targetCollege: "St. Joseph's College of Commerce", status: "New", callConnected: false, source: "College Enquiry", createdAt: daysAgo(3, 16), agent: "Rohit Verma" },
  { id: "l8", name: "Ishita Rao", phone: "+91 97890 66778", email: "ishita.rao@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 45000, lookingFor: "Admission & Campus", targetCollege: "NMIMS University", status: "Application Started", callConnected: true, source: "Scholarship Checker", createdAt: daysAgo(4, 11), agent: "Priya Nair" },
  { id: "l9", name: "Aditya Nair", phone: "+91 98220 88990", email: "aditya.nair@gmail.com", intentLevel: "Cold", scholarshipUnlocked: 16000, lookingFor: "Career Guidance", targetCollege: "National Institute of Design", status: "New", callConnected: false, source: "College Enquiry", createdAt: daysAgo(5, 13), agent: "Rohit Verma" },
  { id: "l10", name: "Meera Joshi", phone: "+91 96325 44556", email: "meera.joshi@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 22000, lookingFor: "Hostel & Fees", targetCollege: "Christ University", status: "Contacted", callConnected: true, source: "Scholarship Checker", createdAt: daysAgo(6, 14), agent: "Priya Nair" },
  { id: "l11", name: "Aditi Kulkarni", phone: "+91 98770 22110", email: "aditi.k@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 30000, lookingFor: "Application Help", targetCollege: "BMS College of Engineering", status: "Offer Received", callConnected: true, source: "Scholarship Checker", createdAt: daysAgo(2, 11), agent: "Rohit Verma" },
  { id: "l12", name: "Farhan Sheikh", phone: "+91 90909 88776", email: "farhan.s@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 28000, lookingFor: "Fee & Application", targetCollege: "Christ University", status: "Admitted", callConnected: true, source: "College Enquiry", createdAt: daysAgo(6, 16), agent: "Rohit Verma" },
  { id: "l13", name: "Aarav Patel", phone: "+91 98765 12345", email: "aarav.patel@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 60000, lookingFor: "MBA Admission & Scholarship", targetCollege: "MYRA School of Business", status: "Application Started", callConnected: true, source: "Scholarship Checker", createdAt: daysAgo(1, 10), agent: "Priya Nair" },
  { id: "l14", name: "Nandita Bora", phone: "+91 98640 22114", email: "nandita.bora@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 48000, lookingFor: "PGDM Fees & Hostel", targetCollege: "Doon Business School", status: "Application Started", callConnected: true, source: "College Enquiry", createdAt: daysAgo(2, 14), agent: "Rohit Verma" },
  { id: "l15", name: "Rahul Das", phone: "+91 99541 77432", email: "rahul.das@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 50000, lookingFor: "MBA Application Help", targetCollege: "GNIOT Institute of Management Studies", status: "Offer Received", callConnected: true, source: "Scholarship Checker", createdAt: daysAgo(4, 12), agent: "Priya Nair" },
  // ─── More Scholarship leads ───
  { id: "l16", name: "Kavya Menon", phone: "+91 98460 11223", email: "kavya.m@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 42000, lookingFor: "MBA Admission & Scholarship", targetCollege: "MYRA School of Business", status: "New", callConnected: false, source: "Scholarship Checker", createdAt: daysAgo(0, 11), agent: "Rohit Verma" },
  { id: "l17", name: "Nikhil Reddy", phone: "+91 97000 33445", email: "nikhil.r@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 35000, lookingFor: "Scholarship & Hostel", targetCollege: "Doon Business School", status: "New", callConnected: false, source: "Scholarship Checker", createdAt: daysAgo(0, 14), agent: "Priya Nair" },
  { id: "l18", name: "Tanvi Bhat", phone: "+91 98800 55667", email: "tanvi.b@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 55000, lookingFor: "Application Help & Scholarship", targetCollege: "NMIMS University", status: "Contacted", callConnected: true, source: "Scholarship Checker", createdAt: daysAgo(1, 11), agent: "Rohit Verma" },
  { id: "l19", name: "Rajesh Kumar", phone: "+91 99010 77889", email: "rajesh.k@gmail.com", intentLevel: "Cold", scholarshipUnlocked: 18000, lookingFor: "General Counselling", targetCollege: "BMS College of Engineering", status: "New", callConnected: false, source: "Scholarship Checker", createdAt: daysAgo(2, 9), agent: "Priya Nair" },
  { id: "l20", name: "Simran Kaur", phone: "+91 98140 99001", email: "simran.k@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 28000, lookingFor: "Fee Structure & Hostel", targetCollege: "Christ University", status: "Contacted", callConnected: true, source: "Scholarship Checker", createdAt: daysAgo(3, 13), agent: "Rohit Verma" },
  // ─── More Enquiry leads ───
  { id: "l21", name: "Pooja Thakur", phone: "+91 98720 22334", email: "pooja.t@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 0, lookingFor: "College Comparison", targetCollege: "Manipal Institute of Technology", status: "New", callConnected: false, source: "College Enquiry", createdAt: daysAgo(0, 12), agent: "Priya Nair" },
  { id: "l22", name: "Suresh Pillai", phone: "+91 99610 44556", email: "suresh.p@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 0, lookingFor: "Admission Process", targetCollege: "RV College of Engineering", status: "Contacted", callConnected: true, source: "College Enquiry", createdAt: daysAgo(1, 10), agent: "Rohit Verma" },
  { id: "l23", name: "Divya Nair", phone: "+91 98470 66778", email: "divya.n@gmail.com", intentLevel: "Warm", scholarshipUnlocked: 0, lookingFor: "MBA Fees & Placements", targetCollege: "Pune Institute of Business Management", status: "New", callConnected: false, source: "College Enquiry", createdAt: daysAgo(2, 15), agent: "Priya Nair" },
  { id: "l24", name: "Amit Singh", phone: "+91 99230 88990", email: "amit.s@gmail.com", intentLevel: "Cold", scholarshipUnlocked: 0, lookingFor: "General Counselling", targetCollege: "GNIOT Institute of Management Studies", status: "Contacted", callConnected: true, source: "College Enquiry", createdAt: daysAgo(3, 11), agent: "Rohit Verma" },
  { id: "l25", name: "Neha Agarwal", phone: "+91 98350 00112", email: "neha.a@gmail.com", intentLevel: "Hot", scholarshipUnlocked: 0, lookingFor: "Application Help", targetCollege: "Delhi Technological University", status: "New", callConnected: false, source: "College Enquiry", createdAt: daysAgo(4, 14), agent: "Priya Nair" },
  // ─── Raw Data leads ───
  { id: "l26", name: "Sourav Borah", phone: "+91 98765 10005", email: "sourav.demo@example.com", intentLevel: "Hot", scholarshipUnlocked: 38000, lookingFor: "B.E. Computer Science", targetCollege: "RV College of Engineering", status: "Contacted", callConnected: true, source: "Imported Raw Data", createdAt: daysAgo(0, 13), agent: "Rohit Verma" },
  { id: "l27", name: "Moumita Baruah", phone: "+91 98765 10008", email: "moumita.demo@example.com", intentLevel: "Warm", scholarshipUnlocked: 22000, lookingFor: "B.E. Computer Science", targetCollege: "BMS College of Engineering", status: "New", callConnected: false, source: "Imported Raw Data", createdAt: daysAgo(0, 15), agent: "Priya Nair" },
  { id: "l28", name: "Rinku Dutta", phone: "+91 98765 10010", email: "rinku.demo@example.com", intentLevel: "Hot", scholarshipUnlocked: 50000, lookingFor: "B.Tech Computer Science", targetCollege: "Manipal Institute of Technology", status: "Application Started", callConnected: true, source: "Imported Raw Data", createdAt: daysAgo(1, 10), agent: "Rohit Verma" },
  { id: "l29", name: "Bedanta Baruah", phone: "+91 98765 10015", email: "bedanta.demo@example.com", intentLevel: "Hot", scholarshipUnlocked: 40000, lookingFor: "PGDM — Finance", targetCollege: "MYRA School of Business", status: "New", callConnected: false, source: "Imported Raw Data", createdAt: daysAgo(0, 10), agent: "Rohit Verma" },
  { id: "l30", name: "Rimjhim Goswami", phone: "+91 98765 10013", email: "rimjhim.demo@example.com", intentLevel: "Warm", scholarshipUnlocked: 25000, lookingFor: "PGDM — Business Analytics", targetCollege: "Pune Institute of Business Management", status: "Contacted", callConnected: true, source: "Imported Raw Data", createdAt: daysAgo(1, 12), agent: "Priya Nair" },
];

export const SEED_LEADS: Lead[] = RAW_SEED_LEADS.map((lead) => ({
  ...lead,
  leadType: lead.source === "Scholarship Checker" ? "scholarship" : lead.source === "College Enquiry" ? "enquiry" : "raw",
  scholarshipApplied: lead.source === "Scholarship Checker",
}));

export const SEED_APPLICATIONS: Application[] = [
  {
    id: "ap1",
    leadId: "l3",
    studentName: "Arjun Mehta",
    phone: "+91 91234 56789",
    collegeId: "manipal",
    collegeName: "Manipal Institute of Technology",
    program: "B.Tech Computer Science",
    scholarshipApplied: 24000,
    stage: "Docs Pending",
    docs: docs(["d1", "d2", "d4"]),
    notes: "Comparing hostel options; needs help with fee payment plan.",
    agent: "Aman Gupta",
    startedAt: daysAgo(1, 16),
    updatedAt: daysAgo(0, 10),
    timeline: [
      { at: daysAgo(1, 16), label: "Application started by Aman Gupta" },
      { at: daysAgo(1, 17), label: "Docs checklist created — awaiting marksheets" },
    ],
  },
  {
    id: "ap2",
    leadId: "l6",
    studentName: "Ananya Gupta",
    phone: "+91 98111 22334",
    collegeId: "dtu",
    collegeName: "Delhi Technological University",
    program: "B.Tech Computer Science",
    scholarshipApplied: 36000,
    stage: "Submitted",
    docs: docs(["d1", "d2", "d3", "d4", "d5", "d6"]),
    notes: "Submitted via JoSAA slot 1. Following up on document verification.",
    agent: "Priya Nair",
    startedAt: daysAgo(3, 11),
    updatedAt: daysAgo(0, 12),
    timeline: [
      { at: daysAgo(3, 11), label: "Application started by Priya Nair" },
      { at: daysAgo(2, 12), label: "All documents uploaded" },
      { at: daysAgo(0, 12), label: "Application submitted — awaiting offer" },
    ],
  },
  {
    id: "ap3",
    leadId: "l8",
    studentName: "Ishita Rao",
    phone: "+91 97890 66778",
    collegeId: "nmims",
    collegeName: "NMIMS University",
    program: "MBA Core",
    scholarshipApplied: 45000,
    stage: "Offer Received",
    docs: docs(["d1", "d2", "d3", "d4", "d5", "d6"]),
    notes: "Offer letter received — NPAT merit round. Needs fee-block guidance.",
    agent: "Sara Khan",
    startedAt: daysAgo(4, 12),
    updatedAt: daysAgo(0, 9),
    timeline: [
      { at: daysAgo(4, 12), label: "Application started by Sara Khan" },
      { at: daysAgo(3, 15), label: "Documents verified & submitted" },
      { at: daysAgo(1, 10), label: "Offer received from NMIMS University" },
    ],
  },
  {
    id: "ap4",
    leadId: "l11",
    studentName: "Aditi Kulkarni",
    phone: "+91 98770 22110",
    collegeId: "bmsce",
    collegeName: "BMS College of Engineering",
    program: "B.E. Information Science",
    scholarshipApplied: 30000,
    stage: "Offer Received",
    docs: docs(["d1", "d2", "d3", "d4", "d5", "d6", "d7"]),
    notes: "COMEDK rank 1,842. Offer received; counselled on fee deposit.",
    agent: "Rohit Verma",
    startedAt: daysAgo(2, 12),
    updatedAt: daysAgo(0, 14),
    timeline: [
      { at: daysAgo(2, 12), label: "Application started by Rohit Verma" },
      { at: daysAgo(1, 16), label: "All documents uploaded" },
      { at: daysAgo(0, 14), label: "Offer received from BMS College of Engineering" },
    ],
  },
  {
    id: "ap5",
    leadId: "l12",
    studentName: "Farhan Sheikh",
    phone: "+91 90909 88776",
    collegeId: "christ",
    collegeName: "Christ University",
    program: "BBA",
    scholarshipApplied: 28000,
    stage: "Admitted",
    docs: docs(["d1", "d2", "d3", "d4", "d5", "d6", "d7"]),
    notes: "Fee deposited — confirmed seat. Handed off to onboarding.",
    agent: "Aman Gupta",
    startedAt: daysAgo(6, 17),
    updatedAt: daysAgo(1, 13),
    timeline: [
      { at: daysAgo(6, 17), label: "Application started by Aman Gupta" },
      { at: daysAgo(4, 14), label: "Documents verified & submitted" },
      { at: daysAgo(3, 12), label: "Offer received from Christ University" },
      { at: daysAgo(1, 13), label: "Admitted — seat confirmed" },
    ],
  },
  {
    id: "ap6",
    leadId: "l13",
    studentName: "Aarav Patel",
    phone: "+91 98765 12345",
    collegeId: "myra",
    collegeName: "MYRA School of Business",
    program: "PGDM — Business Analytics",
    scholarshipApplied: 60000,
    stage: "Docs Pending",
    docs: docs(["d1", "d2", "d4"]),
    notes: "Comparing Finance and Business Analytics tracks. Counsellor shared the MYRA scholarship guide.",
    agent: "Priya Nair",
    startedAt: daysAgo(1, 11),
    updatedAt: daysAgo(0, 10),
    timeline: [
      { at: daysAgo(1, 11), label: "Application started by Priya Nair" },
      { at: daysAgo(1, 12), label: "MYRA PGDM shortlist created — documents pending" },
    ],
  },
  {
    id: "ap7",
    leadId: "l14",
    studentName: "Nandita Bora",
    phone: "+91 98640 22114",
    collegeId: "doon",
    collegeName: "Doon Business School",
    program: "MBA — General Management",
    scholarshipApplied: 48000,
    stage: "Submitted",
    docs: docs(["d1", "d2", "d3", "d4", "d5", "d6"]),
    notes: "Application submitted; awaiting interview slot confirmation from admissions.",
    agent: "Rohit Verma",
    startedAt: daysAgo(2, 15),
    updatedAt: daysAgo(0, 12),
    timeline: [
      { at: daysAgo(2, 15), label: "Application started by Rohit Verma" },
      { at: daysAgo(1, 13), label: "Documents verified and uploaded" },
      { at: daysAgo(0, 12), label: "Application submitted to Doon Business School" },
    ],
  },
  {
    id: "ap8",
    leadId: "l15",
    studentName: "Rahul Das",
    phone: "+91 99541 77432",
    collegeId: "gims",
    collegeName: "GNIOT Institute of Management Studies",
    program: "PGDM — Business Analytics",
    scholarshipApplied: 50000,
    stage: "Offer Received",
    docs: docs(["d1", "d2", "d3", "d4", "d5", "d6", "d7"]),
    notes: "Offer received for the PGDM 2026 intake. Student is reviewing the dual-specialisation options.",
    agent: "Sara Khan",
    startedAt: daysAgo(4, 13),
    updatedAt: daysAgo(0, 9),
    timeline: [
      { at: daysAgo(4, 13), label: "Application started by Sara Khan" },
      { at: daysAgo(2, 14), label: "All documents uploaded and verified" },
      { at: daysAgo(0, 9), label: "Offer received from GIMS Greater Noida" },
    ],
  },
];

export const SEED_ENQUIRIES: Enquiry[] = (() => {
  const rows: Enquiry[] = [];
  const weeks = 8;
  const perWeek = [4, 6, 5, 7, 8, 6, 9, 7];
  let n = 1;
  for (let w = weeks - 1; w >= 0; w--) {
    const count = perWeek[weeks - 1 - w] ?? 5;
    for (let i = 0; i < count; i++) {
      const converted = Math.random() < 0.18;
      const source = i % 3 === 0 ? "College Enquiry" : "Scholarship Checker";
      rows.push({
        id: `e${n++}`,
        createdAt: daysAgo(w * 7 + Math.floor(Math.random() * 6), 9 + (i % 8)),
        converted,
        source,
      });
    }
  }
  return rows;
})();

export const SEED_VOUCHERS: Voucher[] = [
  {
    id: "v1",
    code: "ORN-4F7K-2026",
    studentName: "Demo Student",
    phone: "+91 90000 00000",
    college: "RV College of Engineering",
    program: "B.E. Computer Science",
    amount: 48000,
    issuedAt: daysAgo(3),
    expiresAt: (() => { const d = new Date(); d.setDate(d.getDate() - 3 + 180); return d.toISOString(); })(),
    status: "Active",
    primaryCollege: "RV College of Engineering",
    stream: "Engineering",
    perCollegeBreakdown: [
      { collegeId: "rvce", collegeName: "RV College of Engineering", amount: 48000 },
      { collegeId: "bmsce", collegeName: "BMS College of Engineering", amount: 36000 },
      { collegeId: "christ", collegeName: "Christ University", amount: 36000 },
      { collegeId: "manipal", collegeName: "Manipal Academy of Higher Education", amount: 48000 },
      { collegeId: "nmims", collegeName: "NMIMS University", amount: 48000 },
      { collegeId: "dtu", collegeName: "Delhi Technological University", amount: 36000 },
      { collegeId: "nid", collegeName: "National Institute of Design", amount: 36000 },
      { collegeId: "sjcc", collegeName: "St. Joseph's College of Commerce", amount: 24000 },
    ],
  },
];

export const SEED_STUDENT_PROFILE: StudentProfile = {
  name: "Aarav Patel",
  phone: "+91 98765 12345",
  email: "aarav.patel@gmail.com",
  city: "Bengaluru",
  scoreBand: "90+",
  stream: "Engineering",
};
